### ISSUE TITLE
Users Page

### ISSUE THREAD

**Issue by xedom** [whatasave/codeduel#1]
- [x] whatasave/codeduel#3
- [x] whatasave/codeduel-fe#3
- [x] whatasave/codeduel-be#2
- [x] whatasave/codeduel-fe#4
